# OPA-LTE2PROXY configuration
# Disimpan via: olp setup

LISTEN_ADDR=127.0.0.1:10800
EGRESS_IP=192.168.100.174
MODEM_IFACE=enx00e04c8f6956
API_ADDR=127.0.0.1:10808
ADB_SERIAL=2285100c
AUTO_ROTATE_MINS=0
ROTATE_EVERY_REQS=0
